(LOG-12926) - Desenvolver clique para abrir modal no grafico
comexio/design-system pull request #104
Opened 2021-01-06 17:55 UTC by gustavoraamos

## :package: Conteúdo

- Implementação de ícone lupa para exibição de detalhes no card usado no 
  Ranking de Exportadores
- Implementação de ícone lupa para exibição de detalhes na tabela Detalhes
- Ajustes nas props dos componentes para controle de exibição da lupa
- Criação de eventos personalizados para chamada de modal no expo
- Teste unitário

## :heavy_check_mark: Tarefa(s)

- [LOG-12743](https://logcomex.atlassian.net/browse/LOG-12743)

## :eyes: Link da tarefa de code review:

- [LOG-12927](https://logcomex.atlassian.net/browse/LOG-12927)

2021-01-06 18:08 UTC, lucaslogcomex submitted a review, later dismissed

2021-01-06 18:27 UTC, logklingenfus submitted a review, later dismissed

2021-01-06 18:49 UTC, kauanschaeffer requested changes
Favor atualizar a documentação do componente

2021-01-06 19:22 UTC, kauanschaeffer commented on docs/stories/components/charts/LLinearChartExpand.stories.js
> +    search: {actions: 'search', table: {disable: true}},
O correto é "action", não "actions", porém, como ele está disabled não irá influenciar

2021-01-06 19:27 UTC, kauanschaeffer submitted a review, later dismissed

2021-01-06 19:28 UTC, gustavoraamos commented on docs/stories/components/charts/LLinearChartExpand.stories.js
> +    search: {actions: 'search', table: {disable: true}},
Certo, ajustado! Obrigado.

2021-01-06 19:32 UTC, kauanschaeffer approved these changes

2021-01-06 19:59 UTC, lucaslogcomex approved these changes

2021-01-06 19:59 UTC, logklingenfus approved these changes

2021-01-07 13:52 UTC, kauanschaeffer commented
Feature será transferida para o shared-components.

2021-01-07 13:52 UTC, closed without merging