(LOG-14024) - Design System :: Documentar componente tag
comexio/design-system pull request #107
Opened 2021-01-06 20:31 UTC by matheuzsrlog

## :package: Conteúdo

- Design System :: Documentar componente tag

## :heavy_check_mark: Tarefa(s)

- LOG-14024

## :eyes: Tarefa de Code Review (CR)

- LOG-14491

2021-01-06 20:37 UTC, gustavoraamos commented on docs/stories/components/tags/LTag.stories.js
> +    colorRelation: { control: 'object', description: 'Define o contrast', table: { disable: true }},
```suggestion
    colorRelation: { control: 'object', description: 'Define the contrast', table: { disable: true }},
```

2021-01-06 20:49 UTC, kauanschaeffer requested changes

2021-01-06 20:49 UTC, kauanschaeffer commented on docs/stories/components/tags/LTag.stories.js
> +    label: { control: 'boolean', description: 'Control to define whether the tag will be a label' },
Revisar a description da doc

2021-01-06 20:49 UTC, kauanschaeffer commented on docs/stories/components/tags/LTag.stories.js
> +    outlined: { control: 'boolean', description: 'Control to define whether the tag will be a outlined' },
Revisar description da doc

2021-01-06 20:49 UTC, kauanschaeffer commented on docs/stories/components/tags/LTag.stories.js
> +    removeTag: { action: 'Tag removed', description: 'Event tag removed' },
Alterar a action para o mesmo nome do $emit, revisar description

2021-01-06 20:49 UTC, kauanschaeffer commented on docs/stories/components/tags/LTag.stories.js
> +};
Adicionar mais variantes do componente na doc.

2021-01-07 11:23 UTC, matheuzsrlog commented on docs/stories/components/tags/LTag.stories.js
> +    colorRelation: { control: 'object', description: 'Define o contrast', table: { disable: true }},
Boa, vlw

2021-01-07 11:23 UTC, matheuzsrlog commented on docs/stories/components/tags/LTag.stories.js
> +};
Feito

2021-01-07 11:24 UTC, matheuzsrlog commented on docs/stories/components/tags/LTag.stories.js
> +    outlined: { control: 'boolean', description: 'Control to define whether the tag will be a outlined' },
Feito

2021-01-07 11:24 UTC, matheuzsrlog commented on docs/stories/components/tags/LTag.stories.js
> +    label: { control: 'boolean', description: 'Control to define whether the tag will be a label' },
Feito

2021-01-07 13:18 UTC, kauanschaeffer approved these changes

2021-01-07 13:18 UTC, merged