(LOG-16729) - Adicionar id nos titulos e informações estáticas do componente
comexio/design-system pull request #130
Opened 2021-02-05 18:49 UTC by gustavoraamos

## :package: Conteúdo

- Adição de props para deixar geração de ID condicional
- Implementação de função slugify para gerar i
- Testes unitários
- Documentação

## :heavy_check_mark: Tarefa(s)

- [LOG-16134](https://logcomex.atlassian.net/browse/LOG-16134)

## :eyes: Link da tarefa de code review:

- [LOG-16731](https://logcomex.atlassian.net/browse/LOG-16731)

2021-02-05 19:20 UTC, lucaslogcomex submitted a review, later dismissed

2021-02-05 19:25 UTC, rafaelbastiansch requested changes

2021-02-05 19:25 UTC, rafaelbastiansch commented on utils/string.util.ts
> +export function slugify (string: string) {
fazer teste unitário pra essa função

2021-02-05 19:29 UTC, gustavoraamos commented on utils/string.util.ts
> +export function slugify (string: string) {
Faltou subir, valeu! :+1:

2021-02-05 19:38 UTC, lucaslogcomex approved these changes

2021-02-08 14:14 UTC, rafaelbastiansch approved these changes

2021-02-08 15:00 UTC, merged