(LOG-11364) - Date Picker não funciona no Safari
comexio/design-system pull request #134
Opened 2021-02-09 12:21 UTC by matheuzsrlog

## :package: Conteúdo

- Date Picker não funciona no Safari

## :heavy_check_mark: Tarefa(s)

- LOG-11364

## :eyes: Tarefa de Code Review (CR)

- LOG-16898

2021-02-09 13:14 UTC, kauanschaeffer approved these changes

2021-02-09 18:35 UTC, rafaelbastiansch requested changes

2021-02-09 18:35 UTC, rafaelbastiansch commented on utils/date.util.ts
> +    const date = new Date(periodParsed + ' 12:00')
isso afeta os dois datepickers?

2021-02-09 18:37 UTC, matheuzsrlog commented on utils/date.util.ts
> +    const date = new Date(periodParsed + ' 12:00')
Sim

2021-02-10 13:13 UTC, rafaelbastiansch approved these changes

2021-02-10 13:53 UTC, merged