(LOG-20799) - Search e Expo :: Tabela que traz outros expandido esta quebrando layout padrão
comexio/design-system pull request #148
Opened 2021-03-25 17:18 UTC by gabriel-ward

## :package: Conteúdo

- Alterado css do LLinearchart

## :heavy_check_mark: Tarefa(s)
- [LOG-20799](https://logcomex.atlassian.net/browse/LOG-20799)

## Link da tarefa de code review:
- [LOG-21854](https://logcomex.atlassian.net/browse/LOG-21854)

## :test_tube: Justificativa - No Test Needed
Não é preciso de teste por ser uma alteração de css

2021-03-25 17:44 UTC, CMatheusR-LogComex submitted a review, later dismissed

2021-03-25 18:09 UTC, rafaelbastiansch requested changes

2021-03-25 18:09 UTC, rafaelbastiansch commented on src/components/charts/LLinearChartExpand.vue
> +      max-height: 195px;
da pra setar esse max-heigth por props? seria bom ter essa possibilidade

2021-03-25 18:09 UTC, rafaelbastiansch commented on src/components/charts/LLinearChart.vue
> +    float:right;
ta certo usar float aqui? ainda mais setando direto na .row do vueitfy?

2021-03-25 19:39 UTC, CMatheusR-LogComex approved these changes

2021-03-26 13:24 UTC, rafaelbastiansch approved these changes

2021-03-26 13:33 UTC, merged