(LOG-22525) - Adicionado a opção de clicar no título no LBarChart e LSimpleTable.
comexio/design-system pull request #161
Opened 2021-04-23 12:35 UTC by CMatheusR-LogComex

## :package: Conteúdo

- Adicionado a opção de clicar no título no LBarChart e LSimpleTable.
- Implementado a opção de passar se é um cursor pointer ou não pelas props do LBarChart e LSimpleTable.
## :heavy_check_mark: Tarefa(s)

- LOG-22523

## :eyes: Tarefa de Code Review (CR)

- LOG-22531

2021-04-23 13:24 UTC, jeronimo-rocha approved these changes

2021-04-26 11:39 UTC, jeronimo-rocha approved these changes

2021-04-26 12:23 UTC, pedrologcomex submitted a review, later dismissed

2021-04-26 12:48 UTC, kauanschaeffer commented on src/components/charts/LBarChart.vue
> +      this.$emit('tittleClick', value)
O componente já emite evento de clique em alguma outra parte? Se não, talvez uma boa opção seja manter o evento apenas como "click". Caso não seja viável mudar para "titleClick"

2021-04-26 12:50 UTC, kauanschaeffer commented on src/components/tables/LSimpleTable.vue
> +    tittleClick (value) {
handleTitleClick

2021-04-26 12:50 UTC, kauanschaeffer commented on src/components/tables/LSimpleTable.vue
> +      this.$emit('tittleClick', value)
click ou titleClick

2021-04-26 12:50 UTC, kauanschaeffer commented on src/components/charts/LBarChart.vue
>        :is-last-item="isLastItem(index)"
Incluir novas props e story com essa variante na documentação / teste unitário do que foi feito.

2021-04-26 12:50 UTC, kauanschaeffer commented on src/components/charts/LBarChartLine.vue
>            <span
Incluir novas props e story com essa variante na documentação / teste unitário do que foi feito.

2021-04-26 12:51 UTC, kauanschaeffer commented on src/components/tables/LSimpleTable.vue
>              v-for="(item, index) in data"
Incluir novas props e story com essa variante na documentação / teste unitário do que foi feito.

2021-04-26 14:07 UTC, kauanschaeffer requested changes

2021-04-26 14:07 UTC, kauanschaeffer commented on docs/stories/components/charts/LBarChart.stories.js
> +    isClickable: { default: true },
Colocar control: 'boolean' e description em inglês, sem valor default.
(Colocar na linha 10 antes dos disables.

2021-04-26 14:07 UTC, kauanschaeffer commented on docs/stories/components/charts/LBarChart.stories.js
>  };
1. Adicionar handler no template, algo como @click="click" para que a action seja emitida no storybook.
2. Adicionar nova story, similar à default, porém, com a prop isclickable true. Algo como "TitleClickable" recebendo as mesmas coisas que a default, mas com o isClickable ture.

2021-04-26 14:07 UTC, kauanschaeffer commented on src/components/charts/LBarChartLine.vue
> +      this.$emit('titleClick', value)
Esse vai ficar como titleClick mesmo?

2021-04-26 14:07 UTC, kauanschaeffer commented on test/components/tables/lSimpleTable.spec.ts
> +describe('LTable', () => {
Faltou testar a questão do isClickable/emissão do evento.

2021-04-26 14:07 UTC, kauanschaeffer commented on src/components/charts/LBarChartLine.vue
>            <span
Faltou o teste unitário.

2021-04-26 14:07 UTC, kauanschaeffer commented on src/components/charts/LBarChart.vue
>        :is-last-item="isLastItem(index)"
Faltou o teste unitário.

2021-04-26 14:14 UTC, CMatheusR-LogComex commented on src/components/charts/LBarChartLine.vue
> +      this.$emit('titleClick', value)
Sim, acredito que seja melhor já que é algo mais específico.

2021-04-26 17:30 UTC, kauanschaeffer commented on src/components/charts/LBarChartLine.vue
> +      this.$emit('titleClick', value)
Ok

2021-04-26 18:40 UTC, kauanschaeffer approved these changes

2021-04-26 18:43 UTC, lucaslogcomex approved these changes

2021-04-26 18:43 UTC, jeronimo-rocha approved these changes

2021-04-26 19:08 UTC, merged