(LOG-7852) Implementa chart de importacao do search no DS
comexio/design-system pull request #178
Opened 2021-06-10 19:15 UTC by jonelog

## :package: Conteúdo

- Implementa componente do ds
- cria documentacao
- adiciona unit tests

## :heavy_check_mark: Tarefa(s)

- LOG-7852

## :eyes: Tarefa de Code Review (CR)

- LOG-27283

2021-06-11 16:30 UTC, kauanschaeffer requested changes

2021-06-11 16:30 UTC, kauanschaeffer commented on utils/currency.util.ts
> +import { TYPES_OF_VALUES_FORMAT } from '~/enum/linearChart.enum'
Teste unitario

2021-06-16 19:26 UTC, rafaelbastiansch requested changes

2021-06-16 19:26 UTC, rafaelbastiansch commented on src/components/charts/LLinearChartLine.vue
> +          >{{ showPartition(data) }}</span>
quebrar o span
span>
{{}}
</span>

2021-06-16 19:26 UTC, rafaelbastiansch commented on src/components/charts/LLinearChartTotalValue.vue
> +} from "~/enum/linearChart.enum";
usar aspas simples e sem ;, igual o kauan falou acima, acho que seu eslint ta trollando

2021-06-16 19:26 UTC, rafaelbastiansch commented on src/components/charts/LLinearChartTotalValue.vue
> +        .filter((item) => !(!item.hasOwnProperty('shipmentQuantity') && item.label === "total"))
cara, isso de shipmentQuantity é bem especifico pra logcomex, não deverai estar no DS

2021-06-29 20:41 UTC, jonelog commented on src/components/charts/LLinearChartTotalValue.vue
> +  }
Testei novamente sem ele e nao funfou papi

2021-06-30 19:12 UTC, kauanschaeffer requested changes

2021-06-30 19:12 UTC, kauanschaeffer commented on .vscode/settings.json
> +  }
Acho que esse arquivo não deveria ser commitad

2021-06-30 19:12 UTC, kauanschaeffer commented on docs/stories/components/charts/LLinearChartTotalValue.stories.js
> +  title: 'omponents/Charts/Primary Bar/TotalValue',
```suggestion
  title: 'components/Charts/Primary Bar/TotalValue',
```

2021-06-30 19:12 UTC, kauanschaeffer commented on docs/stories/components/charts/LLinearChartTotalValue.stories.js
> +    totalValue: '1234'
Colocar algum outro valor que faça mais sentido nas labels para o exemplo ficar mais didático

2021-06-30 19:12 UTC, kauanschaeffer commented on src/components/charts/LLinearChartTotalValue.vue
> +  }
não deveria, mas okay..

2021-06-30 19:12 UTC, kauanschaeffer commented on src/components/charts/LLinearChartTotalValue.vue
> +      color: #b8b8b8;
variavel scss

2021-06-30 19:12 UTC, kauanschaeffer commented on test/components/charts/lLinearChartTotalValue.spec.ts
> +  it('render component correctly', async () => {
```suggestion
  it('renders component correctly', async () => {
```

2021-06-30 19:12 UTC, kauanschaeffer commented on test/components/charts/lLinearChartTotalValue.spec.ts
> +  it('render chart correctly', async () => {
```suggestion
  it('renders chart correctly', async () => {
```

2021-06-30 19:12 UTC, kauanschaeffer commented on test/components/charts/lLinearChartTotalValue.spec.ts
> +    expect(chart.exists()).toBeTruthy()
```suggestion
    expect(chart.exists()).toBe(true)
```

2021-06-30 19:12 UTC, kauanschaeffer commented
Não esquece de olhar no chromatic se tá certo (UI Review e UI Test)

2021-06-30 20:00 UTC, kauanschaeffer requested changes

2021-06-30 20:00 UTC, kauanschaeffer commented on docs/stories/components/charts/LLinearChartTotalValue.stories.js
> +  title: 'components/Charts/Primary Bar/TotalValue',
```suggestion
  title: 'components/Charts/Primary Bar/Total Value',
```

2021-06-30 20:00 UTC, kauanschaeffer commented on docs/stories/components/charts/LLinearChartTotalValue.stories.js
> +};
```suggestion
Default.args = {
    data: [{
      label: 'An amazing label here',
      percentage: 95,
      quantity: null,
      value: '4.530,33',
      total: '4.535,00'
    }],
    title: 'An awesome title',
    totalValue: '6.000'
};
```

2021-06-30 20:04 UTC, kauanschaeffer approved these changes

2021-06-30 20:56 UTC, rafaelbastiansch approved these changes

2021-07-14 13:10 UTC, gustavoraamos approved these changes

2021-07-14 13:44 UTC, merged