(LOG-29175) - Alteração nos componentes LCheckboxList
comexio/design-system pull request #183
Opened 2021-06-17 12:36 UTC by matheuzsrlog

## :package: Conteúdo

- Alteração nos componentes para emitir do LCheckboxList
- Alteração nas documentações e no teste
- Incluindo validação na hora da emitir

## :heavy_check_mark: Tarefa(s)

- LOG-29175

## :eyes: Tarefa de Code Review (CR)

- LOG-28423

2021-06-17 12:47 UTC, kauanschaeffer requested changes

2021-06-17 12:47 UTC, kauanschaeffer commented on docs/stories/components/inputs/LCheckboxList.stories.js
> +  template: `<l-checkbox-list v-bind="$props" @input="input" @updatedItems="updatedItems"></l-checkbox-list>`,
Faltou add a action do input

2021-06-17 12:47 UTC, kauanschaeffer commented on docs/stories/components/inputs/LDropdownCheckbox.stories.js
>      selectedItems: {control: 'array', description: 'Optional array containing values of preselected items'},
Qual a diferença desse value pro selectedItems?

2021-06-17 12:47 UTC, kauanschaeffer commented on docs/stories/components/inputs/LDropdownCheckbox.stories.js
> +};
Por que tem 2 default? Esse deveria ter outro nome, e ao invés de passar o v-model tu teria q passar a tua prop

2021-06-17 12:47 UTC, kauanschaeffer commented on src/components/inputs/LCheckboxList.vue
> +      }
Add isso no teste unitario

2021-06-17 14:23 UTC, kauanschaeffer approved these changes

2021-06-25 13:11 UTC, rafaelbastiansch approved these changes

2021-06-25 14:43 UTC, merged