(LOG-29064) - Implementação da lista de itens não clicáveis no LinearChartExpand.
comexio/design-system pull request #184
Opened 2021-06-17 19:59 UTC by CMatheusR-LogComex

## :package: Conteúdo

- Implementação da lista de itens não clicáveis no LinearChartExpand.
- Implementação do Teste unitário.
- Ajuste da validação para o eventClick.

## :heavy_check_mark: Tarefa(s)

- LOG-27413

## :eyes: Tarefa de Code Review (CR)

- LOG-28031

2021-06-21 12:34 UTC, kauanschaeffer requested changes

2021-06-21 12:34 UTC, kauanschaeffer commented on docs/stories/components/charts/LLinearChartExpand.stories.js
>  };
O pointer do cursor e o evento de click não estão sendo emitidos na documentação, pode ser que esteja faltando algo na doc ou seja um problema na implementação.

2021-06-21 12:34 UTC, kauanschaeffer commented on test/components/charts/lLinearChartExpand.spec.ts
>  })
Adicionar teste unitário para assegurar emit do click em caso de item clicável e não emit em caso de item não clicável

2021-06-21 13:34 UTC, CMatheusR-LogComex commented on test/components/charts/lLinearChartExpand.spec.ts
>  })
Não acho que seja necessário, já que o método 'isClickable' do linearChartExpand é o que define se ele vai ser clicável ou não. Ficariam dois testes para a mesma coisa.

2021-06-21 13:35 UTC, CMatheusR-LogComex commented on docs/stories/components/charts/LLinearChartExpand.stories.js
>  };
Corrigido, faltou implementar a função 'applyCursorPointer' que fala que os itens podem ser clicáveis.

2021-06-21 14:14 UTC, rafaelbastiansch approved these changes

2021-06-22 15:27 UTC, kauanschaeffer requested changes

2021-06-22 15:27 UTC, kauanschaeffer commented on test/components/charts/lLinearChartExpand.spec.ts
> +    expect(linearChartExpand.emitted()).toEqual({"eventClick": [["ASCENSUS TRADING LOGISTICA LTDA"]],"hook:beforeCreate": [[]], "hook:beforeMount": [[]], "hook:created": [[]], "hook:mounted": [[]]})
mudar para expect(emitted().eventClick).toBeTruthy()

2021-06-22 15:27 UTC, kauanschaeffer commented on test/components/charts/lLinearChartExpand.spec.ts
> +    expect(linearChartExpand.emitted()).toEqual({"hook:beforeCreate": [[]], "hook:beforeMount": [[]], "hook:created": [[]], "hook:mounted": [[]]})
mudar para expect(emitted().eventClick).toBeFalsy()

2021-06-24 15:51 UTC, kauanschaeffer approved these changes

2021-06-25 11:53 UTC, rafaelbastiansch approved these changes

2021-06-25 12:28 UTC, merged