(LOG-28845) - Cadastro unitário de embarques
comexio/design-system pull request #203
Opened 2021-07-08 13:58 UTC by matheuzsrlog

## :package: Conteúdo

- Implementação do formulário
- Adiciona text área
## :heavy_check_mark: Tarefa(s)

- LOG-28845

## :eyes: Tarefa de Code Review (CR)

- LOG-29061

2021-07-08 16:22 UTC, rafaelbastiansch requested changes
Falta teste unitário pra tudo isso

2021-07-08 16:22 UTC, rafaelbastiansch commented on src/components/inputs/LLabeledTextarea.vue
> +      class="l-labeled-input--input"
classe errada e fora do padrão BEM

2021-07-09 12:06 UTC, moniquedomingues approved these changes

2021-07-09 12:42 UTC, kauanschaeffer requested changes

2021-07-09 12:42 UTC, kauanschaeffer commented on docs/stories/components/inputs/LInputLoaded.stories.js
> +    showInformation: {control: 'boolean', description: 'Displays information at search time'},
Deixar control antes das actions

2021-07-09 12:42 UTC, kauanschaeffer commented on src/components/inputs/LLabeledSelect.vue
> +  name: 'LabeledSelect',
```suggestion
  name: 'LLabeledSelect',
```

2021-07-09 12:42 UTC, kauanschaeffer commented on test/components/inputs/lInputLoaded.spec.ts
> +  it('render component InputLoaded', async () => {
```suggestion
  it('renders component', async () => {
```

2021-07-09 12:42 UTC, kauanschaeffer commented on test/components/inputs/lInputLoaded.spec.ts
> +  it('outline-style text field', async () => {
```suggestion
  it('sets outlined style', async () => {
```

2021-07-09 12:42 UTC, kauanschaeffer commented on test/components/inputs/lInputLoaded.spec.ts
> +  it('render searchOnInput variant correctly', async () => {
```suggestion
  it('renders searchOnInput variant correctly', async () => {
```

2021-07-09 12:42 UTC, kauanschaeffer commented on test/components/inputs/lInputLoaded.spec.ts
> +    expect(tag.message).toBe('blablabla')
Podia colocar outra msg aqui nér? kakak

2021-07-09 12:42 UTC, kauanschaeffer commented on test/components/modal/LModal.spec.ts
> +  it('variant without divider', async () => {
```suggestion
  it('renders variant without divider', async () => {
```

2021-07-09 12:47 UTC, rafaelbastiansch requested changes

2021-07-09 12:47 UTC, rafaelbastiansch commented on src/components/inputs/LInputLoaded.vue
> +        }
identação esta errada

2021-07-09 12:56 UTC, kauanschaeffer approved these changes

2021-07-09 13:50 UTC, gustavoraamos approved these changes

2021-07-09 13:51 UTC, moniquedomingues approved these changes

2021-07-09 13:58 UTC, rafaelbastiansch approved these changes

2021-07-09 13:59 UTC, merged