(LOG-32473) - Adição de tradução do campo no componente LRouteChart
comexio/design-system pull request #215
Opened 2021-07-22 17:29 UTC by fabricio-gomes-log

## :package: Conteúdo

- Adição de tradução do campo no componente LRouteChart

## :heavy_check_mark: Tarefa(s)

- LOG-28509

## :eyes: Tarefa de Code Review (CR)

- LOG-32300

2021-07-22 18:46 UTC, kauanschaeffer approved these changes

2021-07-22 19:29 UTC, CMatheusR-LogComex approved these changes

2021-07-23 13:35 UTC, rafaelbastiansch requested changes

2021-07-23 13:35 UTC, rafaelbastiansch commented on src/components/charts/LRouteChartLine.vue
> +        {{ $t(data.quantity.name) }} : {{ data.quantity.value }}
não faz sentido a tradução aqui, pq não passar o texto da traduzido?

2021-07-26 12:19 UTC, fabricio-gomes-log commented
Após realizar tratativa da tradução no próprio expo/impo, as altera no design system não são mais necessárias.

2021-07-26 12:19 UTC, closed without merging