(LOG-19128) Ajustes no LDatePickerMonth
comexio/design-system pull request #216
Opened 2021-07-22 21:46 UTC by kauanschaeffer

## :package: Conteúdo

- Adição de tradução aos períodos
- Adição de prop itemsColor
- Documentação

## :heavy_check_mark: Tarefa(s)

- LOG-32243

## :eyes: Tarefa de Code Review (CR)

- LOG-32244

2021-07-22 21:54 UTC, gabriel-ward approved these changes

2021-07-22 21:55 UTC, calistroandre approved these changes

2021-07-22 21:56 UTC, gustavoraamos approved these changes

2021-07-23 13:33 UTC, matheuzsrlog requested changes

2021-07-23 13:33 UTC, matheuzsrlog commented on docs/stories/components/inputs/LDatePickerMonth.stories.js
> +        'Object with min and max limits'
```suggestion
      description: 'Object with min and max limits'
```

2021-07-23 13:33 UTC, matheuzsrlog commented on docs/stories/components/inputs/LDatePickerMonth.stories.js
> +        'List of available months to be used as placeholder'
```suggestion
      description: 'List of available months to be used as placeholder'
```

2021-07-23 13:33 UTC, matheuzsrlog approved these changes

2021-07-23 17:35 UTC, rafaelbastiansch requested changes

2021-07-23 17:35 UTC, rafaelbastiansch commented on enum/date.enum.ts
> +  last_12_months: 'datepickerPeriods.last_12_months'
man, temos que tirar dependencia de tradução do DS, alguma sugestão pra isso?

2021-07-23 18:23 UTC, rafaelbastiansch approved these changes

2021-07-23 18:23 UTC, rafaelbastiansch commented on enum/date.enum.ts
> +  last_12_months: 'datepickerPeriods.last_12_months'
isso vai ficar assim por ser algo que vai ser bem treta de tirar agora, mas não sera aceito tradução em componentes novos e vamos tentar tirar dos que ja tem hoje

2021-07-23 19:59 UTC, merged