(LOG-32395) Criação evento de click sobre a linha do BarLineChart para filtro automático
comexio/design-system pull request #217
Opened 2021-07-23 12:22 UTC by log-borica

## :package: Conteúdo

- Criação da ação de click para linha do BarChartLine
- Criação de testes unitários

## :heavy_check_mark: Tarefa(s)

- LOG-31836

## :eyes: Tarefa de Code Review (CR)

- LOG-31954

2021-07-23 12:42 UTC, jeronimo-rocha approved these changes

2021-07-23 14:24 UTC, kauanschaeffer requested changes

2021-07-23 14:24 UTC, kauanschaeffer commented on src/components/charts/LBarChart.vue
> +      @lineClick="handleLineClick(item.description)"
Talvez seja interessante tu não mandar só a description do item, mas o item inteiro, depois aonde tu ter o handler pro evento tu pode usar qualquer uma das informações do item.

2021-07-23 14:24 UTC, kauanschaeffer commented on src/components/charts/LBarChart.vue
> +        this.$emit('click', value)
Não vai dar problema o evento de clique ser o mesmo pra line e pra não-line?

2021-07-23 14:24 UTC, kauanschaeffer commented on src/components/charts/LBarChart.vue
>        :others-label="othersLabel"
Atualizar documentação do componente.

2021-07-23 14:24 UTC, kauanschaeffer commented on src/components/charts/LBarChartLine.vue
> +    @click="(lineClick(data.description))"
mudar nome do método para algo como handleLineClick, tirar os parentesis a mais e validar a questão que comentei de mandar o item inteiro

2021-07-23 14:24 UTC, kauanschaeffer commented on src/components/charts/LBarChartLine.vue
> +        this.$emit('lineClick', value)
evento em kebab-case

2021-07-23 14:24 UTC, kauanschaeffer commented on src/components/charts/LBarChartLine.vue
>      class="LBarChart__list__item pr-0"
Atualizar documentação tb

2021-07-23 14:24 UTC, kauanschaeffer commented on test/components/charts/lBarChart.spec.ts
> +    expect(barChart.emitted().click).toBeTruthy()
```suggestion
    expect(barChart.emitted().click).toBe(true)
```

2021-07-23 14:24 UTC, kauanschaeffer commented on test/components/charts/lBarChart.spec.ts
> +    expect(barChart.emitted().click).toBeFalsy()
Acho que essa assertion não é necessária

2021-07-23 14:24 UTC, kauanschaeffer commented on test/components/charts/lBarChart.spec.ts
> +    expect(lines().length > 0).toBeTruthy()
Aqui seria bom tu testar se o length é o certo ao invés de se é maior que 0

2021-07-23 14:24 UTC, kauanschaeffer commented on test/components/charts/lBarChart.spec.ts
> +    expect(barChart.emitted().click).toEqual([[' UÍSQUES, EM EMBALAGENS DE CAPACIDADE INFERIOR OU IGUAL A 2 LITROS']])
Se preferir, creio que a assertion anterior nem precisa existir pois essa já valida a emissão do evento e o payload.

2021-07-23 15:21 UTC, log-borica commented on src/components/charts/LBarChart.vue
> +      @lineClick="handleLineClick(item.description)"
revisado ✅

2021-07-23 15:21 UTC, log-borica commented on src/components/charts/LBarChart.vue
> +        this.$emit('click', value)
revisado ✅

2021-07-23 15:22 UTC, log-borica commented on src/components/charts/LBarChartLine.vue
> +    @click="(lineClick(data.description))"
revisado ✅

2021-07-23 15:22 UTC, log-borica commented on test/components/charts/lBarChart.spec.ts
> +    expect(barChart.emitted().click).toBeFalsy()
revisado ✅

2021-07-23 15:22 UTC, log-borica commented on test/components/charts/lBarChart.spec.ts
> +    expect(lines().length > 0).toBeTruthy()
revisado ✅

2021-07-23 15:22 UTC, log-borica commented on test/components/charts/lBarChart.spec.ts
> +    expect(barChart.emitted().click).toBeTruthy()
revisado ✅ assertion removida

2021-07-23 15:22 UTC, log-borica commented on test/components/charts/lBarChart.spec.ts
> +    expect(barChart.emitted().click).toEqual([[' UÍSQUES, EM EMBALAGENS DE CAPACIDADE INFERIOR OU IGUAL A 2 LITROS']])
revisado ✅

2021-07-23 18:17 UTC, log-borica commented on src/components/charts/LBarChart.vue
>        :others-label="othersLabel"
revisado ✅

2021-07-23 18:17 UTC, log-borica commented on src/components/charts/LBarChartLine.vue
> +        this.$emit('lineClick', value)
revisado ✅

2021-07-23 18:22 UTC, log-borica commented on src/components/charts/LBarChartLine.vue
>      class="LBarChart__list__item pr-0"
revisado ✅

2021-07-23 20:52 UTC, rafaelbastiansch approved these changes

2021-07-23 22:00 UTC, kauanschaeffer requested changes

2021-07-23 22:00 UTC, kauanschaeffer commented on src/components/charts/LBarChartLine.vue
> +  font-size: 6px;
fonte em rem

2021-07-23 22:00 UTC, kauanschaeffer commented on docs/stories/components/charts/LBarChart.stories.js
> +    lineLink: { control: 'boolean', description: 'Sets onClick event for whole line and return line\'s data' },
Tem que documentar também o evento emitido, o line-link

2021-07-26 12:13 UTC, log-borica commented on test/components/charts/lBarChart.spec.ts
> +
revisado ✅

2021-07-26 12:13 UTC, log-borica commented on test/components/charts/lBarChart.spec.ts
> +    expect(lines().length === 1).toBeTruthy()
revisado ✅

2021-07-26 12:13 UTC, log-borica commented on test/components/charts/lBarChart.spec.ts
> +
revisado ✅

2021-07-26 13:24 UTC, log-borica commented on src/components/charts/LBarChartLine.vue
> +  font-size: 6px;
revisado ✅

2021-07-26 13:24 UTC, log-borica commented on docs/stories/components/charts/LBarChart.stories.js
> +    lineLink: { control: 'boolean', description: 'Sets onClick event for whole line and return line\'s data' },
revisado ✅

2021-07-26 13:28 UTC, kauanschaeffer approved these changes

2021-07-27 18:31 UTC, rafaelbastiansch approved these changes

2021-07-27 18:37 UTC, merged