(LOG-32871) - Correção da chamada de função do PlaceHolder.
comexio/design-system pull request #218
Opened 2021-07-27 18:37 UTC by CMatheusR-LogComex

## :package: Conteúdo

- Correção da chamada de função do PlaceHolder.

## :heavy_check_mark: Tarefa(s)

- LOG-32871

## :eyes: Tarefa de Code Review (CR)

- LOG-XX

2021-07-27 18:41 UTC, fabricio-gomes-log approved these changes

2021-07-27 18:41 UTC, kauanschaeffer requested changes

2021-07-27 18:41 UTC, kauanschaeffer commented on src/components/inputs/LInputLoaded.vue
> +      :placeholder="handlePlaceholder"
@rafaelbastiansch Temos algum motivo pra declarar as props assim? Tendo em vista que já está usando v-bind com o $attrs. 

Obs: Não entendi bem o que é esse handlePlaceholder, não deveria só propagar pro v-combobox? :sos:

2021-07-27 18:47 UTC, kauanschaeffer submitted a review, later dismissed

2021-07-27 18:51 UTC, rafaelbastiansch requested changes

2021-07-27 18:51 UTC, rafaelbastiansch commented on src/components/inputs/LInputLoaded.vue
> +      :placeholder="handlePlaceholder"
é validado se é outlined e adicionado ou não placeholder

2021-07-27 18:51 UTC, rafaelbastiansch commented on src/components/inputs/LInputLoaded.vue
> +      :placeholder="handlePlaceholder"
Fazer teste unitário pra garantir esse funcionamento

2021-07-27 20:37 UTC, kauanschaeffer requested changes

2021-07-27 20:37 UTC, kauanschaeffer commented on test/components/inputs/lInputLoaded.spec.ts
> +  it('handlePlaceholder is to return placeholder', async () => {
Mudar nome do case para algo como "returns placeholder when isnt outlined"

2021-07-27 20:37 UTC, kauanschaeffer commented on test/components/inputs/lInputLoaded.spec.ts
> +  it('handlePlaceholder is to return empty when outline is true', async () => {
Mudar nome do case para algo como "returns empty placeholder when is outlined"

2021-07-27 20:37 UTC, kauanschaeffer commented on test/components/inputs/lInputLoaded.spec.ts
> +    const result = inputLoaded.vm.handlePlaceholder
Evitar chamar detalhes de implementação nos testes, ao invés disso testar se dada a prop o placeholder no wrapper está como deveria.

2021-07-27 20:37 UTC, kauanschaeffer commented on test/components/inputs/lInputLoaded.spec.ts
> +    const result = inputLoaded.vm.handlePlaceholder
Evitar chamar detalhes de implementação nos testes, ao invés disso testar se dada a prop o placeholder no wrapper está como deveria.

2021-07-28 20:15 UTC, kauanschaeffer approved these changes

2021-07-28 20:43 UTC, rafaelbastiansch approved these changes

2021-07-29 12:04 UTC, fabricio-gomes-log approved these changes

2021-07-29 12:51 UTC, merged