(LOG-32853) - Corrigido tag saindo do input ao ter varias
comexio/design-system pull request #220
Opened 2021-07-29 13:40 UTC by rafaelbastiansch

## :package: Conteúdo

- Corrigido tag saindo do input ao ter varias

## :heavy_check_mark: Tarefa(s)

- LOG-32853

## :eyes: Tarefa de Code Review (CR)

- LOG-33015

2021-07-29 13:47 UTC, kauanschaeffer requested changes

2021-07-29 13:47 UTC, kauanschaeffer commented on src/components/inputs/LInputTag.vue
> +        'hide-details': this.hideDetails
A classe não deveria ser algo como LInputTag--hideDetails ?

2021-07-29 13:47 UTC, kauanschaeffer commented on test/components/inputs/lInputTag.spec.ts
> +  it('shows expand item', async () => {
Sugestão: Fazer esse teste com as stories/testting library

2021-07-29 21:32 UTC, rafaelbastiansch commented on test/components/inputs/lInputTag.spec.ts
> +  it('shows expand item', async () => {
Aconteceu alguns erros e foi criado essa task - https://logcomex.atlassian.net/browse/LOG-33124

2021-07-29 21:35 UTC, kauanschaeffer approved these changes

2021-07-29 21:54 UTC, gustavoraamos approved these changes

2021-07-30 13:10 UTC, arllondias approved these changes

2021-07-30 13:12 UTC, moniquedomingues approved these changes

2021-07-30 13:33 UTC, merged