(LOG-33692) - Adicionar limitação por anos no datepicker
comexio/design-system pull request #226
Opened 2021-08-04 19:54 UTC by pedrologcomex

## :package: Conteúdo

- Criado prop para limitar por anos o período de seleção

## :heavy_check_mark: Tarefa(s)

- LOG-32513

## :eyes: Tarefa de Code Review (CR)
- LOG-32820

2021-08-04 20:00 UTC, rafaelbastiansch approved these changes

2021-08-04 20:01 UTC, rafaelbastiansch requested changes
comentei e aprovei sem querer

2021-08-04 20:17 UTC, kauanschaeffer requested changes

2021-08-04 20:17 UTC, kauanschaeffer commented on docs/stories/components/inputs/LDatePickerDay.stories.js
>      rangeDays: {
Troca as aspas duplas por aspas simples

2021-08-04 20:17 UTC, kauanschaeffer commented on docs/stories/components/inputs/LDatePickerDay.stories.js
> +        "Number of days to limit the range after selection of date (this prop has priority over years, if you pass rangeYears and rangeDays props, rangeDays will be used to limit selection)"
Deixar uma parte na mesma linha, fazer igual o description do datepickerStatus

2021-08-04 20:17 UTC, kauanschaeffer commented on docs/stories/components/inputs/LDatePickerDay.stories.js
> +      description:
Uma linha só

2021-08-04 20:33 UTC, matheuzsrlog requested changes

2021-08-04 20:33 UTC, matheuzsrlog commented on src/components/inputs/LDatePickerDay.vue
> +        }
Usar objectLiterals aqui, para eliminar a duplicidade de codigo

2021-08-05 14:20 UTC, rafaelbastiansch approved these changes

2021-08-05 14:29 UTC, kauanschaeffer approved these changes

2021-08-05 14:34 UTC, merged