(LOG-33354) - Componente de checkbox
comexio/design-system pull request #228
Opened 2021-08-06 17:54 UTC by matheuzsrlog

## :package: Conteúdo

- Criação do componente
- Criação de teste
- Criação de documentação

## :heavy_check_mark: Tarefa(s)

- LOG-33354

## :eyes: Tarefa de Code Review (CR)

- LOG-33398

2021-08-06 18:05 UTC, moniquedomingues requested changes

2021-08-06 18:05 UTC, moniquedomingues commented on src/components/inputs/LCheckboxNew.vue
> +<template>
Não ficaria mais sugestivo se o componente se chamasse LCheckboxSingle ou algo nesse sentido? daqui um tempo ele pode deixar de ser 'novo'

2021-08-06 18:50 UTC, kauanschaeffer requested changes

2021-08-06 18:50 UTC, kauanschaeffer commented on docs/stories/components/inputs/LCheckboxNew.stories.js
> +    color: { control: 'color', description: 'Content color' },
```suggestion
    value: { control: 'text', description: 'Input content' },
    color: { control: 'color', description: 'Content color' },
```

2021-08-06 18:50 UTC, kauanschaeffer commented on test/components/inputs/lCheckboxNew.spec.ts
> +import { mount, Wrapper } from '@vue/test-utils'
Testar com a testing library

2021-08-06 19:09 UTC, rafaelbastiansch requested changes

2021-08-06 19:09 UTC, rafaelbastiansch commented on src/components/inputs/LCheckboxNew.vue
> +    class="LCheckboxNew"
o que acha de manter LCheckbox, pra se algo estiver estilizando isso no futuro não quebrar?

2021-08-07 01:57 UTC, matheuzsrlog commented on src/components/inputs/LCheckboxNew.vue
> +    class="LCheckboxNew"
Tá falando sobre a classe?

2021-08-09 12:51 UTC, rafaelbastiansch commented on src/components/inputs/LCheckboxNew.vue
> +    class="LCheckboxNew"
isso

2021-08-09 13:40 UTC, kauanschaeffer requested changes

2021-08-09 13:40 UTC, kauanschaeffer commented on test/components/inputs/lCheckboxNew.spec.ts
> +  })
```suggestion
  it('toggles checkbox state, async () => {
    renderComponent(Default())

    const lCheckboxNew = screen.getByRole('checkbox')
    await userEvent.click(lCheckboxNew)

    expect(lCheckboxNew).toBeChecked()
  })
```

2021-08-09 13:40 UTC, moniquedomingues approved these changes

2021-08-09 13:58 UTC, kauanschaeffer requested changes

2021-08-09 13:58 UTC, kauanschaeffer commented on test/components/inputs/lCheckboxNew.spec.ts
> +
```suggestion
```

2021-08-09 14:02 UTC, kauanschaeffer approved these changes

2021-08-09 14:51 UTC, kauanschaeffer approved these changes

2021-08-09 14:54 UTC, rafaelbastiansch approved these changes

2021-08-09 18:14 UTC, moniquedomingues approved these changes

2021-08-09 20:10 UTC, merged