(LOG-29409) Criação LButtonNew
comexio/design-system pull request #234
Opened 2021-08-16 17:58 UTC by kauanschaeffer

## :package: Conteúdo

- Criação de novo LButton 
- Criação de variantes específicas de acordo com o protótipo
- Nova documentação e testes unitários

## :heavy_check_mark: Tarefa(s)

- LOG-29409

## :eyes: Tarefa de Code Review (CR)

- LOG-34190

2021-08-16 21:15 UTC, rafaelbastiansch requested changes

2021-08-16 21:15 UTC, rafaelbastiansch commented on src/components/buttons/LButtonNew.vue
> +    purple: Boolean,
purple seria um estado?

2021-08-17 12:48 UTC, kauanschaeffer commented on src/components/buttons/LButtonNew.vue
> +    purple: Boolean,
Sim, é uma variante do primary

2021-08-17 14:32 UTC, rafaelbastiansch approved these changes

2021-08-17 14:42 UTC, moniquedomingues approved these changes

2021-08-17 17:26 UTC, gustavoraamos approved these changes

2021-08-17 17:51 UTC, merged