(LOG-35443) Alteração para o trigger do limpar campos filtros funcionar
comexio/design-system pull request #240
Opened 2021-08-23 17:38 UTC by matheuzsrlog

## :package: Conteúdo

- Alteração para o trigger do limpar campos filtros funcionar

## :heavy_check_mark: Tarefa(s)

- LOG-35443

## :eyes: Tarefa de Code Review (CR)

- LOG-28423

2021-08-23 19:10 UTC, rafaelbastiansch requested changes

2021-08-23 19:10 UTC, rafaelbastiansch commented on test/components/inputs/lCheckboxList.spec.ts
> +    expect(checkboxList.vm.$data.selected).toBe(null)
não ia ter o teste pra ver se tem o icone de checkbox marcado?

2021-08-24 12:50 UTC, rafaelbastiansch approved these changes

2021-08-24 13:04 UTC, kauanschaeffer requested changes

2021-08-24 13:04 UTC, kauanschaeffer commented on src/components/inputs/LCheckboxList.vue
> +    selectedItems (val) {
O que é esse val? Talvez sdeja uma boa deixar um nome mais explícito

2021-08-24 13:04 UTC, kauanschaeffer commented on src/components/inputs/LCheckboxList.vue
> +      if(!val) {
```suggestion
      if (!val) {
```

2021-08-24 13:04 UTC, kauanschaeffer commented on test/components/inputs/lCheckboxList.spec.ts
> +describe('lCheckboxList component(clear selectedItems)', () => {
```suggestion
describe('lCheckboxList component (clear selectedItems)', () => {
```

2021-08-24 13:04 UTC, kauanschaeffer commented on test/components/inputs/lCheckboxList.spec.ts
> +  it('triggers items clear selectedItems', async () => {
```suggestion
  it('clears selectedItems with selectedItems prop', async () => {
```

2021-08-24 13:04 UTC, kauanschaeffer commented on test/components/inputs/lCheckboxList.spec.ts
> +    expect(getItemWithChecked(3).exists()).toBe(true)
```suggestion
    const getUncheckedItem = (index: number) => listItems
      .at(index)
      .find('.v-input__control > .v-input__slot > .v-input--selection-controls__input > .mdi-checkbox-blank-outline')

    expect(getUncheckedItem(0).exists()).toBe(true)
    expect(getUncheckedItem(1).exists()).toBe(true)
    expect(getUncheckedItem(2).exists()).toBe(true)
    expect(getUncheckedItem(3).exists()).toBe(true)
```

2021-08-24 13:22 UTC, kauanschaeffer approved these changes

2021-08-24 13:32 UTC, jonatamr approved these changes

2021-08-24 13:49 UTC, gustavoraamos approved these changes

2021-08-24 13:55 UTC, merged