(LOG-35499) Melhorando mecanismo height LButtonNew
comexio/design-system pull request #243
Opened 2021-08-24 14:15 UTC by kauanschaeffer

## :package: Conteúdo

- Ajustando mecanismo já existente para conseguir reutilizar no LButtonNew

## :heavy_check_mark: Tarefa(s)

- LOG-35499

## :eyes: Tarefa de Code Review (CR)

- LOG-35611

2021-08-24 16:34 UTC, rafaelbastiansch requested changes

2021-08-24 16:34 UTC, rafaelbastiansch commented on src/components/buttons/LButtonNew.vue
> +  font-size: 14px;
deveria ser em REM

2021-08-24 17:05 UTC, kauanschaeffer commented on src/components/buttons/LButtonNew.vue
> +  font-size: 14px;
Explicado no slack, mas só pra documentar: As fontes são em px pois o botão tem tamanho fixo, desta forma, as fontes também precisam ter.

2021-08-24 17:16 UTC, matheuzsrlog requested changes

2021-08-24 17:16 UTC, matheuzsrlog commented on utils/size.util.ts
> +}
Usar "object literals".
Ex: 
```
const { large, small, custom } = heightOption

const optionsHeights =  [large, small, custom]

for(...)
```

Faça um for of, caso não tenha necessariamente que usar o return, use forEatch, lembre de se chegar no final do for tem que retornar o default

2021-08-24 18:39 UTC, rafaelbastiansch approved these changes

2021-08-24 20:53 UTC, rafaelbastiansch approved these changes

2021-08-25 12:29 UTC, matheuzsrlog approved these changes

2021-08-25 12:46 UTC, moniquedomingues approved these changes

2021-08-25 12:51 UTC, merged