(LOG-30634) - Add tooltip component
comexio/design-system pull request #246
Opened 2021-08-31 18:18 UTC by rafaelbastiansch

## :package: Conteúdo

- Add tooltip component

## :heavy_check_mark: Tarefa(s)

- LOG-30634

## :eyes: Tarefa de Code Review (CR)

- LOG-36350

2021-08-31 18:45 UTC, gustavoraamos commented on package.json
> +    "@logcomex/design": "^1.3.0",
Aqui poderia manter a abertura para novas versões?

2021-08-31 18:46 UTC, gustavoraamos commented on yarn.lock
> +"@logcomex/design@^1.3.0":
Aqui também. Apesar de ser DS para DS. Caso estiver correto, favor desconsiderar :+1:

2021-08-31 18:47 UTC, gustavoraamos commented on test/components/tooltip/tooltip.spec.ts
> +
```suggestion

```

2021-08-31 18:49 UTC, rafaelbastiansch commented on package.json
> +    "@logcomex/design": "^1.3.0",
cara, nesse caso sim, não tem problema estar atualizado, é até melhor

2021-08-31 18:50 UTC, rafaelbastiansch commented on yarn.lock
> +"@logcomex/design@^1.3.0":
respondido na de cima

2021-08-31 18:51 UTC, gustavoraamos approved these changes

2021-08-31 19:37 UTC, kauanschaeffer requested changes

2021-08-31 19:37 UTC, kauanschaeffer commented on test/components/tooltip/tooltip.spec.ts
> +const {
```suggestion

const {
```

2021-08-31 19:37 UTC, kauanschaeffer commented on test/components/tooltip/tooltip.spec.ts
> +describe('LButtonNew', () => {
```suggestion
describe('LTooltip', () => {
```

2021-08-31 19:37 UTC, kauanschaeffer commented on docs/stories/components/tooltip/LTooltip.stories.js
> +})
Acho que podemos deletar esse tooltip de exemplo e manter só o exemplo com os quatro tooltips na tela, ele já cumpre bem o papel de documentar.

2021-08-31 19:37 UTC, kauanschaeffer commented on docs/stories/components/tooltip/LTooltip.stories.js
> +          >Left</l-button-new>
Manter texto numa linha sozinho e alterar para "Button" ou para "Hover me"

2021-08-31 19:37 UTC, kauanschaeffer commented on docs/stories/components/tooltip/LTooltip.stories.js
> +          <span>Left tooltip</span>
Colocar algum outro texto, o de cima por exemplo "My tooltip title" e o de baixo "My tooltip text"

2021-08-31 19:42 UTC, rafaelbastiansch commented on docs/stories/components/tooltip/LTooltip.stories.js
> +          <span>Left tooltip</span>
mas eles não tem tamanho diferentes, não seria um titulo, tudo é conteúdo, faz sentido?

2021-08-31 19:48 UTC, rafaelbastiansch commented on test/components/tooltip/tooltip.spec.ts
> +  it('renders default tooltip', async () => {
não existe role de tooltip nesse cara, ele não renderiza o template que é passado, inspecionando no browser ele é adicionado fora do componente, por isso imagino que não é criado dentro dele no teste também.

2021-08-31 19:48 UTC, rafaelbastiansch commented on test/components/tooltip/tooltip.spec.ts
> +  it('render multiple tooltips', () => {
resposta acima

2021-08-31 19:50 UTC, rafaelbastiansch commented on src/components/tooltip/LTooltip.vue
> +        'LTooltip LTooltip--pointer': true,
isso é obrigatório ter, seria o css base do componente

2021-08-31 19:53 UTC, rafaelbastiansch commented on src/components/charts/LCircularChart.vue
> +  },
ele é um componente interno, o correto seria usar o import

2021-08-31 19:53 UTC, rafaelbastiansch commented on src/components/charts/LRouteChartLine.vue
> +  },
mesma resposta

2021-08-31 19:54 UTC, rafaelbastiansch commented on src/components/tooltip/LTooltip.vue
> +  <v-tooltip
a classe padrão do tooltip é no content-class

2021-08-31 19:57 UTC, rafaelbastiansch commented on src/components/tooltip/LTooltip.vue
> +    <template
sim, ele só tem o activator e default

2021-08-31 20:46 UTC, kauanschaeffer commented on docs/stories/components/tooltip/LTooltip.stories.js
> +          <span>Left tooltip</span>
Sim, de fato, na real que não sei se é necessário esse divider com mais conteúdo em baixo, está assim por conta do protótipo? Daria pra deixar só um "My tooltip text", que é o padrão, um tooltip só com o conteúdo.
Qualquer coisa dá pra adicionar um outro com mais coisa junto.

Aí ficaria um dos tooltips normal só o texto, outro com o divider, daria pra adicionar um com icone, algo assim, tlg?

2021-08-31 20:51 UTC, rafaelbastiansch commented on docs/stories/components/tooltip/LTooltip.stories.js
> +          <span>Left tooltip</span>
então, o conteudo quem passa é quem vai usar, pode ser qualquer coisa.

2021-08-31 20:55 UTC, kauanschaeffer requested changes

2021-08-31 20:55 UTC, kauanschaeffer commented on docs/stories/components/tooltip/LTooltip.stories.js
> +      description: 'Boolean to programatically shows tooltip'
```suggestion
      description: 'Toggles tooltip visibility'
```

2021-08-31 20:55 UTC, kauanschaeffer commented on docs/stories/components/tooltip/LTooltip.stories.js
> +      description: 'Emitted when tooltip shows/hide'
```suggestion
      description: 'Emitted when tooltip hover is toggled'
```

2021-08-31 20:55 UTC, kauanschaeffer commented on docs/stories/components/tooltip/LTooltip.stories.js
> +    activator: { description: 'Slot to use to toggle tooltip on hover, otherwise you need to toogle it programatically using v-model' },
```suggestion
    activator: { description: 'Slot to toggle tooltip on hover, without it you need to toogle programatically using v-model' },
```

2021-08-31 20:55 UTC, kauanschaeffer commented on docs/stories/components/tooltip/LTooltip.stories.js
> +    default: { description: 'Default slot with content to shows on tooltip' }
```suggestion
    default: { description: 'Default slot with tooltip content' }
```

2021-08-31 20:55 UTC, kauanschaeffer commented on src/components/tooltip/LTooltip.vue
> +        'LTooltip LTooltip--pointer': true,
Não seria uma boa deixar essas classes no template? Apenas pra diferenciar as props customizáveis das padrão?

2021-08-31 20:55 UTC, kauanschaeffer commented on src/components/tooltip/LTooltip.vue
> +
```suggestion
      const formattedClasses = Object.keys(componentClasses)
        .filter(className => !isNil(componentClasses[className])).join(' ')

```

2021-08-31 20:55 UTC, kauanschaeffer commented on src/components/tooltip/LTooltip.vue
> +      const componentClasses = {
```suggestion
      const availableClasses = {
```

2021-08-31 20:55 UTC, kauanschaeffer commented on src/components/tooltip/LTooltip.vue
> +      const componentClasses = {
Não sei se available é o melhor nome,  dria pra pensar em outro

2021-08-31 20:55 UTC, kauanschaeffer commented on src/components/tooltip/LTooltip.vue
> +      return formattedClassesNameToString
```suggestion
      return formattedClasses
```

2021-08-31 20:55 UTC, kauanschaeffer commented on docs/stories/components/tooltip/LTooltip.stories.js
> +const TemplateMultipleTooltips = (args, { argTypes }) => ({
```suggestion
const Template = (args, { argTypes }) => ({
```

2021-08-31 20:55 UTC, kauanschaeffer commented on docs/stories/components/tooltip/LTooltip.stories.js
> +export const MultipleTooltips = TemplateMultipleTooltips.bind({})
```suggestion
export const Tooltips = Template.bind({})
```

2021-08-31 20:55 UTC, kauanschaeffer commented on docs/stories/components/tooltip/LTooltip.stories.js
> +MultipleTooltips.args = {}
```suggestion
Tooltips.args = {}
```

2021-08-31 21:07 UTC, rafaelbastiansch commented on src/components/tooltip/LTooltip.vue
> +        'LTooltip LTooltip--pointer': true,
não tem como deixar no template, content-class é um prop, diferente do class que vc pode deixar um padrão

2021-09-01 12:45 UTC, kauanschaeffer requested changes

2021-09-01 12:45 UTC, kauanschaeffer commented on test/components/tooltip/lTooltip.spec.ts
> +} = composeStories(stories)
```suggestion
const { Tooltips } = composeStories(stories)
```

2021-09-01 12:45 UTC, kauanschaeffer commented on test/components/tooltip/lTooltip.spec.ts
> +  it('render multiple tooltips', () => {
```suggestion
  it('renders multiple tooltips from story', () => {
```

2021-09-01 12:45 UTC, kauanschaeffer commented on test/components/tooltip/lTooltip.spec.ts
> +  it('render tooltip and check slot content', () => {
```suggestion
  it('renders tooltip and its slot content', () => {
```

2021-09-01 13:01 UTC, kauanschaeffer approved these changes

2021-09-01 13:23 UTC, gustavoraamos approved these changes

2021-09-01 15:03 UTC, moniquedomingues approved these changes

2021-09-01 15:05 UTC, merged