(LOG-36630) - Alterado tooltip padrão nos gráficos
comexio/design-system pull request #250
Opened 2021-09-02 20:46 UTC by rafaelbastiansch

## :package: Conteúdo

- Alterado tooltip padrão nos gráficos

## :heavy_check_mark: Tarefa(s)

- LOG-36630

## :eyes: Tarefa de Code Review (CR)

- LOG-36953

2021-09-02 21:17 UTC, patriciatoassi approved these changes

2021-09-02 21:19 UTC, gustavoraamos submitted a review, later dismissed

2021-09-02 23:01 UTC, matheuzsrlog requested changes

2021-09-02 23:01 UTC, matheuzsrlog commented on src/components/charts/LBarChartLine.vue
> +                      {{ isLastItem ? $t('ayla.others') : data.description }}
o que acha de fazer uma computed para isso?

2021-09-02 23:01 UTC, matheuzsrlog commented on src/components/charts/LBarChartLine.vue
>                      {{ translation.total || $t('ayla.total') }}: {{ data.total }} USD
Se puder aqui tbm

2021-09-02 23:01 UTC, matheuzsrlog commented on src/components/charts/LBarChartLine.vue
>                      {{ translation.quantity || $t('ayla.quantity') }}: {{ data.quantity }}
Se puder aqui tbm

2021-09-03 14:39 UTC, matheuzsrlog approved these changes

2021-09-08 14:28 UTC, gustavoraamos approved these changes

2021-09-08 14:43 UTC, patriciatoassi approved these changes

2021-09-08 14:48 UTC, merged