(LOG-38458) Adição prop iconColors LTableNew
comexio/design-system pull request #256
Opened 2021-09-17 19:53 UTC by kauanschaeffer

## :package: Conteúdo

- Adição de prop para possibilitar customizar as cores dos icones da table

## :heavy_check_mark: Tarefa(s)

- LOG-38458

## :eyes: Tarefa de Code Review (CR)

- LOG-37235

2021-09-17 19:58 UTC, moniquedomingues submitted a review, later dismissed

2021-09-17 20:24 UTC, gustavoraamos approved these changes

2021-09-17 20:29 UTC, matheuzsrlog requested changes

2021-09-17 20:29 UTC, matheuzsrlog commented on src/components/tables/LTableNew.vue
> +    :style="{ '--iconColorActive': iconColors.active, '--iconColorInactive': iconColors.inactive }"
colocar em uma computed

2021-09-17 20:43 UTC, rafaelbastiansch commented on src/components/tables/LTableNew.vue
> +    :style="{ '--iconColorActive': iconColors.active, '--iconColorInactive': iconColors.inactive }"
isso é pra alterar a cor do icone de select?

2021-09-17 20:52 UTC, kauanschaeffer commented on src/components/tables/LTableNew.vue
> +    :style="{ '--iconColorActive': iconColors.active, '--iconColorInactive': iconColors.inactive }"
Cor do checkbox e cor dos icones de ordenar a coluna

2021-09-17 22:19 UTC, matheuzsrlog approved these changes

2021-09-20 12:17 UTC, gustavoraamos approved these changes

2021-09-20 18:44 UTC, moniquedomingues approved these changes

2021-09-20 18:44 UTC, lucaslogcomex approved these changes

2021-09-20 18:57 UTC, rafaelbastiansch approved these changes

2021-09-20 19:24 UTC, merged