(LOG-37060) Ajustando acessibilidade dos inputs
comexio/design-system pull request #280
Opened 2021-10-29 19:36 UTC by kauanschaeffer

## :package: Conteúdo

- Adição inheritAttrsFalse para prevenir que tenham atributos em duplicidade i.e. ids
- Adição aria-label ao LTextField para que ele possa ser encontrado pela label mesmo recebendo id

## :heavy_check_mark: Tarefa(s)

- LOG-37060

## :eyes: Tarefa de Code Review (CR)

- LOG-42470

2021-10-29 19:38 UTC, arllondias approved these changes

2021-10-29 19:38 UTC, rodrigobrill-logcomex submitted a review, later dismissed

2021-10-29 19:50 UTC, moniquedomingues approved these changes

2021-10-29 19:57 UTC, matheuzsrlog requested changes

2021-10-29 19:57 UTC, matheuzsrlog commented on src/components/inputs/LCombobox.vue
Teste unitário?

2021-10-29 20:03 UTC, kauanschaeffer commented on src/components/inputs/LCombobox.vue
A princípio achei que não fazia sentido testar pois isso não altera a funcionalidade/visual/utilização do componente. Mas acho que vai ser uma boa garantir do nosso lado, pois assim se alguém alterar ele vai falhar o teste.

2021-10-29 20:17 UTC, matheuzsrlog approved these changes

2021-10-29 20:18 UTC, rodrigobrill-logcomex approved these changes

2021-11-01 12:42 UTC, AndreFontouraLC approved these changes

2021-11-01 12:52 UTC, merged