(LOG-41633) Melhorias estilização do LButtonNew
comexio/design-system pull request #286
Opened 2021-11-10 17:38 UTC by kauanschaeffer

## :package: Conteúdo

- Adição de mecanismo para tornar o LButtonNew mais customizável/dinâmico
- Remoção de props/classes/estilos descontinuados
- Novas props: roundedIcon e buttonColors
- Melhorias doc / ajustes nos testes unitários

## :heavy_check_mark: Tarefa(s)

- LOG-41633

## :eyes: Tarefa de Code Review (CR)

- LOG-43131

2021-11-10 19:08 UTC, rafaelbastiansch requested changes

2021-11-10 19:08 UTC, rafaelbastiansch commented on src/components/buttons/LButtonNew.vue
> +        borderDisabled: null
se isso default é null, pq passar as chaves?

2021-11-10 19:09 UTC, kauanschaeffer commented on src/components/buttons/LButtonNew.vue
> +        borderDisabled: null
Apenas pra documentar, pois pega os valores no storybook e se alguém olhar o código dá pra identificar o que essa prop recebe sem precisar procurar o código.

2021-11-10 19:12 UTC, rafaelbastiansch commented on src/components/buttons/LButtonNew.vue
> +        borderDisabled: null
blz

2021-11-10 19:12 UTC, rafaelbastiansch approved these changes

2021-11-10 20:02 UTC, calistroandre approved these changes

2021-11-10 20:08 UTC, matheuzsrlog requested changes

2021-11-10 20:31 UTC, matheuzsrlog submitted a review, later dismissed

2021-11-10 20:32 UTC, calistroandre approved these changes

2021-11-10 21:25 UTC, rafaelbastiansch approved these changes

2021-11-11 13:21 UTC, rafaelbastiansch approved these changes

2021-11-11 13:36 UTC, matheuzsrlog approved these changes

2021-11-11 13:50 UTC, calistroandre approved these changes

2021-11-11 14:00 UTC, merged