(LOG-43048)  - Implementação da imagem no lCardHeader.
comexio/design-system pull request #297
Opened 2021-11-22 20:31 UTC by CMatheusR-LogComex

## :package: Conteúdo

- Implementação da imagem no lCardHeader.
- Implementação da Chamada ao Clickar na imagem.

## :heavy_check_mark: Tarefa(s)

- LOG-42652

## :eyes: Tarefa de Code Review (CR)
- LOG-43050

2021-11-22 20:41 UTC, kauanschaeffer requested changes

2021-11-22 20:41 UTC, kauanschaeffer commented on src/components/cards/LCardHeader.vue
> +    <div
Isso poderia ficar num slot, não?

2021-11-22 20:43 UTC, matheuzsrlog requested changes

2021-11-22 20:43 UTC, matheuzsrlog commented on src/components/cards/LCardHeader.vue
> +      return this.$emit('toggleImage')
Altera o nome do evento p/ `toggle-image`

2021-11-22 20:43 UTC, matheuzsrlog commented on src/components/cards/LCardHeader.vue
> +      console.log(this.imageTooltip)
Remover esse console.log

2021-11-22 20:43 UTC, matheuzsrlog commented on src/components/cards/LCardHeader.vue
> +    <div
O que tu acha de passar via slot esse dado?

2021-11-22 20:43 UTC, matheuzsrlog commented on src/components/cards/LCardHeader.vue
> +    cursor: pointer;
```suggestion
  }
  
  &__image {
    cursor: pointer;
```

2021-11-22 23:52 UTC, CMatheusR-LogComex commented on src/components/cards/LCardHeader.vue
> +    <div
Perfeito, alterado para um slot, Obrigado pela sugestão.

2021-11-22 23:53 UTC, CMatheusR-LogComex commented on src/components/cards/LCardHeader.vue
> +      return this.$emit('toggleImage')
Evento foi removido, mudei o componente para um slot para ficar mais dinâmico conforme a avaliação o pessoal do front.

2021-11-22 23:53 UTC, CMatheusR-LogComex commented on src/components/cards/LCardHeader.vue
> +    <div
Evento foi removido, mudei o componente para um slot para ficar mais dinâmico conforme a avaliação o pessoal do front.

2021-11-22 23:53 UTC, CMatheusR-LogComex commented on src/components/cards/LCardHeader.vue
> +    cursor: pointer;
Evento foi removido, mudei o componente para um slot para ficar mais dinâmico conforme a avaliação o pessoal do front.

2021-11-22 23:53 UTC, CMatheusR-LogComex commented on src/components/cards/LCardHeader.vue
> +      console.log(this.imageTooltip)
Evento foi removido, mudei o componente para um slot para ficar mais dinâmico conforme a avaliação o pessoal do front.

2021-11-23 12:45 UTC, kauanschaeffer requested changes

2021-11-23 12:45 UTC, kauanschaeffer commented on src/components/cards/LCard.vue
> +        <slot name="LCardHeaderSlot" />
```suggestion
        <slot name="header" />
```

2021-11-23 12:45 UTC, kauanschaeffer commented on src/components/cards/LCard.vue
> +        'LCard--grid': this.hasTitleOrDescription
Qual o propósito dessa classe?

2021-11-23 13:05 UTC, CMatheusR-LogComex commented on src/components/cards/LCard.vue
> +        'LCard--grid': this.hasTitleOrDescription
Ela seta a sombra do card e/ou se vai ser uma grid com o tittle e descrição. Foi apagado o espaço do final da linha apenas, acredito que quando eu rodei para dar uma organizada no codigo.

2021-11-23 13:05 UTC, CMatheusR-LogComex commented on src/components/cards/LCard.vue
> +        <slot name="LCardHeaderSlot" />
Alterado, Obrigado.

2021-11-23 13:35 UTC, kauanschaeffer requested changes

2021-11-23 13:35 UTC, kauanschaeffer commented on docs/stories/components/cards/LCard.stories.js
> +    header: { description: "LCardHeader content slot" },
```suggestion
    header: { description: "Header content slot" },
```

2021-11-23 13:35 UTC, kauanschaeffer commented on docs/stories/components/cards/LCard.stories.js
> +    header: { description: "LCardHeader content slot" },
Criar também uma story de exemplo

2021-11-23 14:42 UTC, kauanschaeffer approved these changes

2021-11-23 14:52 UTC, matheuzsrlog approved these changes

2021-11-23 14:57 UTC, rafaelbastiansch approved these changes

2021-11-23 16:06 UTC, merged