(LOG-41465) Criação do ChartGrid
comexio/design-system pull request #336
Opened 2022-02-21 13:51 UTC by biaLogcomex

## :package: Conteúdo

- Adicionando novo chart - ChartGrid
- Documentação
- Testes Unitários

## :heavy_check_mark: Tarefa(s)

- (LOG-41465)

## :eyes: Tarefa de Code Review (CR)

- (LOG-41465)

2022-02-21 14:34 UTC, rafaelbastiansch requested changes

2022-02-21 14:34 UTC, rafaelbastiansch commented on src/components/charts/LChartGrid.vue
> +        <v-icon color="#2E264D">
essa cor poderia estar como uma props para ser dinamica

2022-02-21 14:34 UTC, rafaelbastiansch commented on src/components/charts/LChartGrid.vue
> +  font-family: Rubik;
não precisa especificar a fonte aqui

2022-02-21 14:34 UTC, rafaelbastiansch commented on src/components/charts/LChartGrid.vue
> +  border-bottom: 1px solid #e1dfea;
usar variavel de cor

2022-02-21 14:34 UTC, rafaelbastiansch commented on src/components/charts/LChartGrid.vue
> +    border-right: 1px solid #2e264d;
usar variavel de cor

2022-02-21 14:34 UTC, rafaelbastiansch commented on src/components/charts/LChartGrid.vue
> +    align-items: center;
usar classes de helper do vuetify para substituir essas

2022-02-21 14:34 UTC, rafaelbastiansch commented on src/components/charts/LChartGrid.vue
> +    align-items: center;
d-flex, justify-center, align-center

2022-02-21 14:34 UTC, rafaelbastiansch commented on src/components/charts/LChartGrid.vue
> +    justify-content: start;
aqui tbm https://vuetifyjs.com/en/styles/flex/#flex-justify

2022-02-21 14:34 UTC, rafaelbastiansch commented on src/components/charts/LChartGrid.vue
> +    justify-content: center;
aqui tbm https://vuetifyjs.com/en/styles/flex/#flex-justify

2022-02-21 14:34 UTC, rafaelbastiansch commented on test/components/charts/lChartGrid.spec.ts
> +  // TODO: Falta finalizar o teste do conteúdo interno do chart
quando vai ser feito esse teste?

2022-02-21 14:44 UTC, biaLogcomex commented on src/components/charts/LChartGrid.vue
> +        <v-icon color="#2E264D">
verade, vou arrumar! muito obrigada

2022-02-21 14:45 UTC, biaLogcomex commented on test/components/charts/lChartGrid.spec.ts
> +  // TODO: Falta finalizar o teste do conteúdo interno do chart
Ops eu fiz só nao retirei o TODO sorry

2022-02-21 14:54 UTC, kauanschaeffer requested changes

2022-02-21 14:54 UTC, kauanschaeffer commented on docs/stories/components/charts/LChartGrid.stories.js
> +  template: '<l-chart-grid v-bind="$props"/>'
```suggestion
  template: `
    <l-chart-grid v-bind="$props" />
  `
```
Veja se o github não cagou a identação

2022-02-21 14:54 UTC, kauanschaeffer commented on docs/stories/components/charts/LChartGrid.stories.js
> +import LChartGrid from '~/src/components/charts/LChartGrid.vue';
Todos os componentes de chart usam o padrão LNomeComponenteChart, precisamos manter o mesmo padrão nesse.
Ao invés de LChartGrid deveria se chamar LGridChart.

2022-02-21 14:54 UTC, kauanschaeffer commented on docs/stories/components/charts/LChartGrid.stories.js
> +  title: 'Components/Charts/ChartGrid',
Aqui vai ficar Grid Chart (colocar com espaço)

2022-02-21 14:54 UTC, kauanschaeffer commented on docs/stories/components/charts/LChartGrid.stories.js
> +    { label:'Frete', icon: 'mdi-truck-cargo-container' }
Manter exemplos mais genéricos e em inglês

2022-02-21 14:54 UTC, kauanschaeffer commented on src/components/charts/LChartGrid.vue
> +  <div class="chartGrid">
Classe deveria ser com o nome do componente "LGridChart"

2022-02-21 14:54 UTC, kauanschaeffer commented on src/components/charts/LChartGrid.vue
> +        v-for="(value, key) in headers"
Ao invés de usar "value" usar "header" para ficar mais claro no que tu está iterando.

2022-02-21 14:54 UTC, kauanschaeffer commented on src/components/charts/LChartGrid.vue
> +      v-for="(value, key) in data"
Usar outra coisa oa invés de value, inclusive, ao invés de data poderia ser outro nome também, talvez "rows" ou "items"

2022-02-21 14:54 UTC, kauanschaeffer commented on src/components/charts/LChartGrid.vue
> +        v-for="(subValue, newKey) in value.values"
O que é esse subValue? e o value.values? Seria bom ver outros nomes pois não está muito claro o que está sendo iterado.

2022-02-21 14:54 UTC, kauanschaeffer commented on src/components/charts/LChartGrid.vue
> +  justify-items: center;
Seria bom ver se o justify-items tem alguma classe util do vuetify pra substituir tb

2022-02-21 14:54 UTC, kauanschaeffer commented on src/components/charts/LChartGrid.vue
> +  font-style: normal;
font-style: normal é redundante.

2022-02-21 14:54 UTC, kauanschaeffer commented on test/components/charts/lChartGrid.spec.ts
> +describe('LResumeChart', () => {
Aqui tem que ter o nome desse componente

2022-02-21 14:54 UTC, kauanschaeffer commented on test/components/charts/lChartGrid.spec.ts
> +  it('should contain the side titles', () => {
Ao invés de "contain" eu usaria o termo "render", "should render the side titles", mas se não achar pertinente dá pra manter assim.

2022-02-21 14:54 UTC, kauanschaeffer commented on test/components/charts/lChartGrid.spec.ts
> +    const maximum = screen.getByText('Máximo')
Tu pode usar o getByText já na assertion já que naõ vai usar esses valores em nenhum outro lugar

2022-02-21 14:54 UTC, kauanschaeffer commented on test/components/charts/lChartGrid.spec.ts
> +  it('should contain the top titles', () => {
Usaria render aqui também

2022-02-21 14:54 UTC, kauanschaeffer commented on test/components/charts/lChartGrid.spec.ts
> +    const safe = container.querySelector('.mdi-safe-square-outline')
Os top titles são só icones?

2022-02-21 14:54 UTC, kauanschaeffer commented on test/components/charts/lChartGrid.spec.ts
> +   it('values returned in the chart', () => {
O nome desse teste não faz sentido, seria bom deixar mais claro o que de fato está sendo testado, exemplo: renders chart rows

2022-02-22 14:46 UTC, biaLogcomex commented on src/components/charts/LChartGrid.vue
> +    border-right: 1px solid #2e264d;
utilizando ja! obrigada

2022-02-22 14:46 UTC, biaLogcomex commented on docs/stories/components/charts/LChartGrid.stories.js
> +  template: '<l-chart-grid v-bind="$props"/>'
arrumado!

2022-02-22 14:47 UTC, biaLogcomex commented on docs/stories/components/charts/LChartGrid.stories.js
> +import LChartGrid from '~/src/components/charts/LChartGrid.vue';
Bacana, realmente nem percebi no momento, obrigada!

2022-02-22 14:47 UTC, biaLogcomex commented on docs/stories/components/charts/LChartGrid.stories.js
> +  title: 'Components/Charts/ChartGrid',
Arrumado!

2022-02-22 20:28 UTC, biaLogcomex commented
Todas alterações solicitadas nos request changes foram aplicadas, obriga a todos os envolvidos!

2022-02-22 21:08 UTC, moniquedomingues submitted a review, later dismissed

2022-02-22 21:09 UTC, kauanschaeffer requested changes

2022-02-22 21:09 UTC, kauanschaeffer commented on src/components/charts/LGridChart.vue
> +        v-for="(item, itemKey) in row.values"
Aqui tu poderia chamar ao invés de values  como items também, faz sentido?

2022-02-22 21:09 UTC, kauanschaeffer commented on src/components/charts/LGridChart.vue
> +          {{ header.icon }} mr-2
esse mr-2 não deveria estar aqui

2022-02-22 21:09 UTC, kauanschaeffer commented on src/components/charts/LGridChart.vue
> +  &__icon{
```suggestion
  &__icon {
```

2022-02-22 21:09 UTC, kauanschaeffer commented on src/components/charts/LGridChart.vue
> +  font-style: normal;
font-style normal é redundante (acho que já tinha apontado isso no CR anterior)

2022-02-22 21:09 UTC, kauanschaeffer commented on test/components/charts/lGridChart.spec.ts
> +  it('should render the top titles', () => {
Se achar pertinente, talvez faça sentido ao invés de chamar de "titles" chamar da mesma nomenclatura usada nas props "rows" e "headers"

2022-02-22 21:12 UTC, gustavoraamos submitted a review, later dismissed

2022-02-23 12:08 UTC, biaLogcomex commented on test/components/charts/lGridChart.spec.ts
> +  it('should render the top titles', () => {
opa, verdarde, vou fazer a alteração

2022-02-23 12:08 UTC, biaLogcomex commented on src/components/charts/LGridChart.vue
> +          {{ header.icon }} mr-2
ajeitei kk obrigada

2022-02-23 12:08 UTC, biaLogcomex commented on src/components/charts/LGridChart.vue
> +  &__icon{
ops! obrigadão

2022-02-23 12:43 UTC, biaLogcomex commented on src/components/charts/LGridChart.vue
> +        v-for="(item, itemKey) in row.values"
Faz sim, vou ajustar como está no seacrh para poder utilizar! obrigada pela ideia

2022-02-23 12:58 UTC, kauanschaeffer approved these changes

2022-02-23 13:09 UTC, cassiologcomex approved these changes

2022-02-23 14:23 UTC, merged