(LOG-52573) - Ajuste de espaçamento
comexio/design-system pull request #349
Opened 2022-03-14 19:24 UTC by biaLogcomex

## :package: Conteúdo

- Ajustes nos espaçamentos

## :heavy_check_mark: Tarefa(s)

- LOG-52573

## :eyes: Tarefa de Code Review (CR)

- LOG-52573

2022-03-14 19:35 UTC, biaLogcomex commented on src/components/charts/LGeneralChart.vue
> +      <img
Realmente, vou atualizar kaua

2022-03-14 19:44 UTC, moniquedomingues approved these changes

2022-03-14 19:46 UTC, kauanschaeffer submitted a review, later dismissed

2022-03-14 19:55 UTC, klingenfus submitted a review, later dismissed

2022-03-14 19:59 UTC, rafaelbastiansch approved these changes

2022-03-14 20:14 UTC, matheuzsrlog approved these changes

2022-03-14 20:15 UTC, rafaelbastiansch approved these changes

2022-03-14 20:31 UTC, rafaelbastiansch requested changes

2022-03-14 20:31 UTC, rafaelbastiansch commented on src/components/charts/LGeneralChart.vue
>  <template>
quebrou o percy [https://percy.io/c6f29798/design-system/builds/16496730/changed/928357840?browser[…]requested&viewLayout=overlay&viewMode=new&width=1280&widths=1280](https://percy.io/c6f29798/design-system/builds/16496730/changed/928357840?browser=chrome&browser_ids=18%2C20&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1280&widths=1280)

2022-03-15 19:47 UTC, matheuzsrlog approved these changes

2022-03-16 11:32 UTC, cassiologcomex approved these changes

2022-03-16 13:17 UTC, merged