(LOG-57518) Trazer data em formato americano
comexio/design-system pull request #374
Opened 2022-05-18 22:05 UTC by alexandrealfaLog

## :package: Conteúdo

- Ajuste no formato de data americano do datepicker.

## :heavy_check_mark: Tarefa(s)

- [LOG-57518](https://logcomex.atlassian.net/browse/LOG-57518)

## :eyes: Tarefa de Code Review (CR)

- [LOG-58338](https://logcomex.atlassian.net/browse/LOG-58338)

## :warning: Tipo de alteração

- [ ] Bug fix (não tem breaking change e resolve um bug) 
- [ ] Feature (não tem breaking change e adiciona nova(s) funcionalidade(s) ou componente(s)) 
- [ ] Breaking change (fix ou feature que faz com que uma funcionalidade já existente não funcione mais parcialmente ou totalmente)
- [ ] Melhoria/Refatoração (não tem breaking change, não adiciona nenhuma feature nova e nem corrige bug, no entanto, melhora a qualidade do código, documentação ou alguma outra coisa)
 
## :white_check_mark: Checklist

- [ ] Minha alteração não inclui regras de negócio 
- [ ] Meu código está de acordo com o [Vue Style Guide](https://v2.vuejs.org/v2/style-guide/?redirect=true) e o mais limpo possível 
- [ ] Feature anotada na release note 
- [ ] Testes de snapshot passaram/foram aprovados 
- [ ] Documentação atualizada  
- [ ] Testes unitários atualizados  
- [ ] Levantamento de componentes atualizado 
- [ ] Tenho pelo menos 1 approve de alguém experiente no projeto (ex. membro da equipe de Design System)

2022-05-18 22:18 UTC, CMatheusR-LogComex approved these changes

2022-05-19 11:51 UTC, gustavoraamos approved these changes

2022-05-19 11:51 UTC, fabricio-gomes-log approved these changes

2022-05-19 13:17 UTC, rafaelbastiansch requested changes

2022-05-19 13:17 UTC, rafaelbastiansch commented on enum/datepicker.enum.ts
> +  [LOCALES.EN]: 'MM/DD/YYYY'
de onde veio essa ideia?

2022-05-19 13:30 UTC, kauanschaeffer approved these changes

2022-05-19 13:38 UTC, alexandrealfaLog commented on enum/datepicker.enum.ts
> +  [LOCALES.EN]: 'MM/DD/YYYY'
A ideia veio dessa task : https://logcomex.atlassian.net/browse/LOG-57518
O formato : https://www.google.com/search?q=date+format+usa

2022-05-19 14:17 UTC, merged