(LOG-59582) Substituindo input depreciado e add alerta de depreciação
comexio/design-system pull request #393
Opened 2022-06-09 20:55 UTC by kauanschaeffer

## :package: Conteúdo

- Substituindo uso do LInputSolo que será removido em breve
- Subindo warn na utilização do LDropdownCheck que está marcado para remoção

## :heavy_check_mark: Tarefa(s)

- LOG-59582

## :eyes: Tarefa de Code Review (CR)

- LOG-59875

## :warning: Tipo de alteração

- [ ] Bug fix (não tem breaking change e resolve um bug) 
- [ ] Feature (não tem breaking change e adiciona nova(s) funcionalidade(s) ou componente(s)) 
- [ ] Breaking change (fix ou feature que faz com que uma funcionalidade já existente não funcione mais parcialmente ou totalmente)
- [ ] Melhoria/Refatoração (não tem breaking change, não adiciona nenhuma feature nova e nem corrige bug, no entanto, melhora a qualidade do código, documentação ou alguma outra coisa)
 
## :white_check_mark: Checklist

- [ ] Minha alteração não inclui regras de negócio 
- [ ] Meu código está de acordo com o [Vue Style Guide](https://v2.vuejs.org/v2/style-guide/?redirect=true) e o mais limpo possível 
- [ ] Feature anotada na release note 
- [ ] Testes de snapshot passaram/foram aprovados 
- [ ] Documentação atualizada  
- [ ] Testes unitários atualizados  
- [ ] Levantamento de componentes atualizado 
- [ ] Tenho pelo menos 1 approve de alguém experiente no projeto (ex. membro da equipe de Design System)

2022-06-09 20:57 UTC, rafaelbastiansch submitted a review, later dismissed

2022-06-10 12:23 UTC, matheuzsrlog requested changes

2022-06-10 12:23 UTC, matheuzsrlog commented on src/components/inputs/LCheckboxList.vue
> +        class="LCheckboxList__input"
```suggestion
        class="LCheckboxList__input" 
```
Só remove esse espaço aqui que pegou a mais

2022-06-10 12:23 UTC, matheuzsrlog commented on src/components/inputs/LDropdownCheck.vue
> +      console.warn('LDropdownCheck is deprecated and will be removed in the future')
Se vamos usar sempre esse cara, o que acha de criar uma função para isso? Tipo setDeprecated, ou algo semelhante. Pensa no caso que queiramos mudar a msg

2022-06-10 12:58 UTC, kauanschaeffer commented on src/components/inputs/LDropdownCheck.vue
> +      console.warn('LDropdownCheck is deprecated and will be removed in the future')
Achei que a gente já tivesse conversado sobre isso ser uma função e tals, mas o que eu penso é o seguinte:

> Tinha falado sobre isso com o MP, pode ser uma boa, mas não sei se precisa. Como a ideia é jogar fora os componentes que não fazem sentido e depois não precisar ficar depreciando, não vejo sentido em criar uma estrutura pra isso, seja ela uma função ou até um mixin
https://github.com/comexio/design-system/pull/384#discussion_r889297081

2022-06-10 13:19 UTC, matheuzsrlog approved these changes

2022-06-10 13:26 UTC, rafaelbastiansch approved these changes

2022-06-10 13:31 UTC, moniquedomingues approved these changes

2022-06-10 14:14 UTC, merged