(LOG-72571) - Correção do DatePickerMonth quando lida com data apenas de ano e mês.
comexio/design-system pull request #432
Opened 2023-01-18 18:45 UTC by CMatheusR-LogComex

## :package: Conteúdo

- Correção da seleção de data através dos props laterais de 3, 6, 9 e 12 meses que quando é enviado somente a data e ano para o componete LDatePickerMonth, ele traz um mês anterior do suposto.

## :heavy_check_mark: Tarefa(s)

- [LOG-72047](https://logcomex.atlassian.net/browse/LOG-72047)

## :eyes: Tarefa de Code Review (CR)

- [LOG-72574](https://logcomex.atlassian.net/browse/LOG-72574)

## :warning: Tipo de alteração

- [x] Bug fix (não tem breaking change e resolve um bug) 
- [ ] Feature (não tem breaking change e adiciona nova(s) funcionalidade(s) ou componente(s)) 
- [ ] Breaking change (fix ou feature que faz com que uma funcionalidade já existente não funcione mais parcialmente ou totalmente)
- [ ] Melhoria/Refatoração (não tem breaking change, não adiciona nenhuma feature nova e nem corrige bug, no entanto, melhora a qualidade do código, documentação ou alguma outra coisa)
 
## :white_check_mark: Checklist

- [x] Minha alteração não inclui regras de negócio 
- [x] Meu código está de acordo com o [Vue Style Guide](https://v2.vuejs.org/v2/style-guide/?redirect=true) e o mais limpo possível 
- [x] Feature anotada na release note 
- [ ] Testes de snapshot passaram/foram aprovados 
- [ ] Documentação atualizada  
- [x] Testes unitários atualizados  
- [ ] Levantamento de componentes atualizado

2023-01-18 19:05 UTC, kauanschaeffer requested changes

2023-01-18 19:05 UTC, kauanschaeffer commented on test/components/inputs/lDatePickerMonth.spec.ts
> +describe('datePicker component when have only year and month', () => {
Já que tu criou uma suite nova, por que não montou o teste com a testing library?

2023-01-19 12:28 UTC, kauanschaeffer approved these changes

2023-01-19 12:33 UTC, EduardoFelipeLogcomex approved these changes

2023-01-19 12:57 UTC, merged