(LOG-80171) - Adicionando slot no footer da modal
comexio/design-system pull request #437
Opened 2023-06-21 19:39 UTC by moniquedomingues

## :package: Conteúdo

- Add slot
- Add documentação
- Add testes

## :heavy_check_mark: Tarefa(s)

- LOG-80171

## :eyes: Tarefa de Code Review (CR)

- LOG-XX

## :warning: Tipo de alteração

- [ ] Bug fix (não tem breaking change e resolve um bug) 
- [ ] Feature (não tem breaking change e adiciona nova(s) funcionalidade(s) ou componente(s)) 
- [ ] Breaking change (fix ou feature que faz com que uma funcionalidade já existente não funcione mais parcialmente ou totalmente)
- [x] Melhoria/Refatoração (não tem breaking change, não adiciona nenhuma feature nova e nem corrige bug, no entanto, melhora a qualidade do código, documentação ou alguma outra coisa)
 
## :white_check_mark: Checklist

- [ ] Minha alteração não inclui regras de negócio 
- [ ] Meu código está de acordo com o [Vue Style Guide](https://v2.vuejs.org/v2/style-guide/?redirect=true) e o mais limpo possível 
- [ ] Feature anotada na release note 
- [ ] Testes de snapshot passaram/foram aprovados 
- [ ] Documentação atualizada  
- [ ] Testes unitários atualizados  
- [ ] Levantamento de componentes atualizado

2023-06-21 19:51 UTC, biaLogcomex approved these changes

2023-06-21 20:22 UTC, gustavoraamos approved these changes

2023-06-21 20:22 UTC, gustavoraamos commented on docs/stories/components/modals/LModalFooterNew.stories.js
> +
```suggestion
```
Remover esta linha :smile:

2023-06-22 18:12 UTC, log-abc submitted a review, later dismissed

2023-06-22 18:14 UTC, fabio-luiz-94 approved these changes

2023-06-22 18:15 UTC, matheuzsrlog requested changes

2023-06-22 18:15 UTC, matheuzsrlog commented on docs/stories/components/modals/LModalFooterNew.stories.js
> +}
Como ta repetindo esses caras, vale criar uma const para concentrar em um só local

2023-06-22 18:55 UTC, fabio-luiz-94 approved these changes

2023-06-22 18:58 UTC, CezarRodrigues approved these changes

2023-06-22 19:59 UTC, matheuzsrlog approved these changes

2023-06-22 20:00 UTC, matheuzsrlog approved these changes

2023-06-27 20:14 UTC, merged