(LOG-13773) - Correção de dia máximo para ano mês
comexio/design-system pull request #90
Opened 2020-12-17 17:03 UTC by jeronimo-rocha

## :package: Conteúdo

 - Correção de dia máximo para ano mês

## :heavy_check_mark: Tarefa(s)

- LOG-11990

## :eyes: Tarefa de Code Review (CR)

- LOG-12202

2020-12-17 17:30 UTC, rafaelbastiansch requested changes

2020-12-17 17:30 UTC, rafaelbastiansch commented on utils/date.util.ts
> +    const maxDayOfMonth = new Date(parseInt(year), parseInt(month), 0)
isso ele retorna o ultimo dia do mês?

2020-12-17 17:30 UTC, rafaelbastiansch commented on utils/date.util.ts
> +    const maxDayOfMonth = new Date(parseInt(year), parseInt(month), 0)
corrigir o warning do lint

2020-12-18 14:37 UTC, jeronimo-rocha commented on utils/date.util.ts
> +    const maxDayOfMonth = new Date(parseInt(year), parseInt(month), 0)
Por incrível que pareça, retorna o último dia certinho.

2020-12-18 14:39 UTC, rafaelbastiansch commented on utils/date.util.ts
> +    const maxDayOfMonth = new Date(parseInt(year), parseInt(month), 0)
kkkkkkkk boa

2020-12-18 14:44 UTC, rafaelbastiansch approved these changes

2020-12-18 14:56 UTC, merged